sonar.projectKey=roadmap
sonar.projectName=Roadmap

sonar.sources=app,components,lib,types

sonar.tests=tests,e2e

sonar.exclusions=\
node_modules/**,\
.next/**,\
drizzle/**,\
public/**,\
coverage/**

sonar.test.inclusions=\
tests/**/*.ts,\
tests/**/*.tsx,\
e2e/**/*.ts,\
e2e/**/*.tsx