kind: Deployment
apiVersion: apps/v1

metadata:
  name: roadmap-deployment
  namespace: roadmap
  labels:
    app: roadmap

spec:
  replicas: 2
  selector:
    matchLabels: 
      app: roadmap
  template:
    metadata:
      name: roadmap-pods
      namespace: roadmap
      labels:
        app: roadmap
    spec:
      containers:
        - name: roadmap-ai-app
          image: shashank971/roadmap-ai:latest
          ports: 
            - containerPort:  3000       

          envFrom:
            - secretRef:
                name: roadmap-secrets
          env:
            - name: HOSTNAME
              value: "0.0.0.0"      

          startupProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 5
            failureThreshold: 12     
            
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3    

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3  

          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"  