kind: Secret
apiVersion: v1

metadata:
  name: secrets
  namespace: example

type: Opaque  

stringData:
    AUTH_SECRET: "add yours"
    TURSO_DATABASE_URL: "add your"
    TURSO_AUTH_TOKEN: "add your"
