name: CODE TEST

on:
  workflow_call:

jobs:
  code_test:
    runs-on: ubuntu-latest

    steps:

      # ---------------- CODE CHECKOUT ----------------
      - name: code checkout
        uses: actions/checkout@v7

      # ---------------- NODE.JS ----------------
      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: install dependency
        run: npm ci

      # ---------------- UNIT TESTS ----------------
      - name: code test for node
        run: npm run test

      # ---------------- PLAYWRIGHT ----------------
      - name: install playwright
        run: npx playwright install --with-deps chromium

      # ---------------- E2E DATABASE ----------------
      - name: setup e2e database
        run: npm run db:push
        env:
          SQLITE_PATH: sqlite.e2e.db

      # ---------------- E2E TESTS ----------------
      - name: code test for e2e
        run: npm run test:e2e