name: DEVSECOPS

on:
  push:
    branches: [master]

jobs:
  code_quality:
    uses: ./.github/workflows/code_quality.yml

  secrets_scanning:
    uses: ./.github/workflows/secrets_scanning.yml  

  dependency_check:
    uses: ./.github/workflows/dependency_check.yml    

  docker_scan:
    uses: ./.github/workflows/docker_scan.yml  
    secrets: inherit

  code_test:
    uses:  ./.github/workflows/code_test.yml          